package com.technexus.demand.domain;

public enum DemandState {
	DRAFT, PENDING_REVIEW, APPROVED, REJECTED, PUBLISHED, NEGOTIATING, CONFIRMED, IN_PROGRESS, DELIVERED, COMPLETED, EXPIRED, CANCELLED, OFFLINE
}
