ALTER TABLE tn_article_version MODIFY COLUMN title VARCHAR(160) NOT NULL;
ALTER TABLE tn_post_version MODIFY COLUMN title VARCHAR(160) NOT NULL;
ALTER TABLE tn_demand MODIFY COLUMN title VARCHAR(160) NOT NULL;
